//GET
GET http://localhost:5187/tasks

###

//GET
GET http://localhost:5187/tasks/1

###

POST http://localhost:5187/tasks/
Content-Type: application/json

{
  "title": "quendi api",
  "description": "zrobic api dla quendiego",
  "iscompleted": false

}
###
PUT http://localhost:5187/tasks/9
Content-Type: application/json

{
  "title": "quendi api",
  "description": "zrobic api dla quendiego",
  "iscompleted": true
}
###
//DELETE
DELETE http://localhost:5187/tasks/9

###